data:
  path: /tmp/input_with_rollout.parquet
  medium_difficulty_output_path: /tmp/medium_difficulty_train.parquet
  hard_difficulty_output_path: /tmp/hard_difficulty_train.parquet
  medium_difficulty_filter_bound: [0.51, 0.9]
  hard_difficulty_filter_bound: [0.09, 0.5]
  balance_should_end: true
  should_end_column: "reward_model.ground_truth.should_end"
  reward_score_column: "reward_score"
